### PR TITLE
layouts/partials: fix meta for exp

### PR DESCRIPTION
**Pull request by kortschak**
Fixes issue noted [here](https://github.com/gonum/website/pull/21#issuecomment-458809730).

Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
TBR @sbinet @btracey

Merging because this fixes documentation links.

**Review by sbinet — COMMENTED** [review]
LGTM

**Comment by kortschak** [comment]
I used `for pkg in $(go list ./...); do curl -X POST -d "path=${pkg}" https://godoc.org/-/refresh; done` to refresh the godoc since it was still broken after this update.

**Comment by sbinet** [comment]
perhaps this could be captured as a new tool under `gonum.org/v1/tools` ?
(to run the update concurrently with _e,g,_ 5 concurrent jobs?)

**Comment by kortschak** [comment]
That is `parallel -j5 'curl -X POST -d "path={}" https://godoc.org/-/refresh' ::: $(go list ./...)`.

**Comment by sbinet** [comment]
your shell-fu is stronger than mine :)

just for fun, here is what I came up with:
- https://github.com/go-hep/hep/blob/master/ci/update-godoc.go

**Pull request merged**
