### PR TITLE
fix broken link to numpy intro

### PR DESCRIPTION
**Pull request by mewmew**

### CODE REVIEW

**Comment by btracey** [comment]
LGTM

In the future we should wait for an okay before committing.

**Comment by mewmew** [comment]
Sure, I was a bit trigger happy. Just felt like an easy and obvious fix. Had it been larger, e.g. changing content instead of fixing a link, I'd obviously had waited for review.

**Comment by btracey** [comment]
Yea, I'm not sure what the policy should be, I'm certainly more than happy for others to help with the website. I feel like it's better to stick with the safe version unless it becomes a problem.

**Comment by mewmew** [comment]
> I feel like it's better to stick with the safe version unless it becomes a problem.

Sounds good.

**Pull request merged**
