### PR TITLE
Change numeric to numerical on home page

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
To make @vladimir-ch and @kortschak  happy.

**Review by vladimir-ch — APPROVED** [review]
I'll be even happier if it's changed also in the repository description at https://github.com/gonum/gonum

**Comment by kortschak** [comment]
In that position is should be "numerics" to prevent it being interpreted as the plain adjective; "numerical libraries" seems odd to me (I think it's the number, but maybe that's just me).

**Comment by btracey** [comment]
@kortschak is that in reference to this change or the additional one requested?

**Comment by sbinet** [comment]
not a native speaker (so grain of salt), but: "the" book is called "numerical recipes in C/C++/Fortran".
not "numerics". :)

**Comment by kortschak** [comment]
@btracey, not this is for the package summary on github.

@sbinet you are right, when I look it is again, it's OK; weak local minima and saddles are interesting.

**Comment by btracey** [comment]
@kortschak  So I should merge this?

Also, I reserve the right to make this mistake in the future. Best I can tell this is a pond issue (or the bigger pond issue in Dan and my case).

**Review by kortschak — APPROVED** [review]

**Comment by kortschak** [comment]
>Best I can tell this is a pond issue (or the bigger pond issue in Dan and my case).

This reminds me of the apocryphal Times headline "Channel Fogbound - Continent Isolated".

**Pull request merged**
