### PR TITLE
Use http instead of https until DNS issue is resolved

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
PTAL @Kunde21

**Comment by btracey** [comment]
Background: There seems to be an issue with the SSL certificate I was issued. It works with `www.gonum.org`, but not with `gonum.org`. I've filed a support ticket with netlify, but I think until then we can re-enable `go get`, etc. by just having `http` instead of `https`

**Review by Kunde21 — APPROVED** [review]
LGTM

**Comment by btracey** [comment]
Okay, not a permanent fix, but now `go get -u -t -insecure gonum.org/v1/gonum/...` works for those who need to download the code.

**Pull request merged**
